#!/usr/bin/guile \
-e main -s
!#

(use-modules (expand)
	     (comp)
	     (ice-9 match))

;; ./main test0
(define (main args)
  (apply macroexpand-file (cdr args))
  (apply comp-file (cdr args)))





